# docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/examples/nextjs-app-router'
      - '/examples/react'
      - '/examples/studio'
      - '/examples/studio-i18n'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 2
    groups:
      security:
        applies-to: security-updates
        patterns: ['*']
      updates:
        applies-to: version-updates
        patterns: ['*']

    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 1
    groups:
      all:
        patterns: ['*']
