name: Enforce PR labels

on:
  pull_request:
    types: [ labeled, unlabeled, opened, edited, synchronize ]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          REQUIRED_LABELS_ANY: "feature,bugfix,maintenance,no-release-notes"
          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['feature','bugfix','maintenance','no-release-notes']"
